select
    `hash`,
    nonce,
    transaction_index,
    from_address,
    to_address,
    value,
    gas,
    gas_price,
    input,
    receipt_cumulative_gas_used,
    receipt_gas_used,
    receipt_contract_address,
    receipt_root,
    receipt_status,
    block_timestamp,
    block_number,
    block_hash,
    max_fee_per_gas,
    max_priority_fee_per_gas,
    transaction_type,
    receipt_effective_gas_price,
    max_fee_per_blob_gas,
    ARRAY_TO_STRING(blob_versioned_hashes, ',') as blob_versioned_hashes,
    receipt_blob_gas_price,
    receipt_blob_gas_used
from `bigquery-public-data.crypto_ethereum.transactions`